// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Vercel(Neon) 連携で発行された変数は .env.local にある。
// Prisma CLI は自動で読まないため明示的に読み込む（.env.local を優先）。
loadEnv({ path: ".env" });
loadEnv({ path: ".env.local", override: true });

// db push / migrate 等の DDL は非プール接続を使う（Neon 推奨）。
const cliUrl =
  process.env["DATABASE_URL_UNPOOLED"] ||
  process.env["POSTGRES_URL_NON_POOLING"] ||
  process.env["DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: cliUrl,
  },
});
